[server]
address = "127.0.0.1"
headless = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showErrorDetails = "type"

[theme]
base = "light"
primaryColor = "#3559B8"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F8FA"
textColor = "#161B26"
font = "sans serif"
